/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_Persistence_Service_STUB_HPP_
#define COMMONAPI_Persistence_Service_STUB_HPP_

#include <functional>




#include <v1_0/commonapi/PersistenceService.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <vector>

#include <CommonAPI/Stub.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace commonapi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service PersistenceService. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class PersistenceServiceStubAdapter
    : virtual public CommonAPI::StubAdapter, 
      public PersistenceService {
 public:



    virtual void deactivateManagedInstances() = 0;
protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for PersistenceService.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class PersistenceServiceStubRemoteEvent
{
public:
    virtual ~PersistenceServiceStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service PersistenceService to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class PersistenceServiceStub
    : public virtual CommonAPI::Stub<PersistenceServiceStubAdapter, PersistenceServiceStubRemoteEvent>
{
public:
    typedef std::function<void ()>storeReply_t;
    typedef std::function<void (std::string _value)>loadReply_t;

    virtual ~PersistenceServiceStub() {}
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId) = 0;


    /// This is the method that will be called on remote calls on the method store.
    virtual void store(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _key, std::string _value, storeReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method load.
    virtual void load(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _key, loadReply_t _reply) = 0;

    using CommonAPI::Stub<PersistenceServiceStubAdapter, PersistenceServiceStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<PersistenceServiceStubAdapter, PersistenceServiceStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<PersistenceServiceStubAdapter, PersistenceServiceStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef PersistenceServiceStubRemoteEvent RemoteEventType;
    typedef PersistenceService StubInterface;
};

} // namespace commonapi
} // namespace v1_0

#endif // COMMONAPI_Persistence_Service_STUB_HPP_
