/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_Persistence_Service_DBUS_PROXY_HPP_
#define COMMONAPI_Persistence_Service_DBUS_PROXY_HPP_

#include <v1_0/commonapi/PersistenceServiceProxyBase.hpp>
#include "v1_0/commonapi/PersistenceServiceDBusDeployment.hpp"

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusAddress.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusProxy.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

#include <string>

namespace v1_0 {
namespace commonapi {

class PersistenceServiceDBusProxy
    : virtual public PersistenceServiceProxyBase, 
      virtual public CommonAPI::DBus::DBusProxy {
public:
    PersistenceServiceDBusProxy(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection);

    virtual ~PersistenceServiceDBusProxy() { }



    virtual void store(const std::string &_key, const std::string &_value, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info);
    virtual std::future<CommonAPI::CallStatus> storeAsync(const std::string &_key, const std::string &_value, StoreAsyncCallback _callback, const CommonAPI::CallInfo *_info);
    virtual void load(const std::string &_key, CommonAPI::CallStatus &_internalCallStatus, std::string &_value, const CommonAPI::CallInfo *_info);
    virtual std::future<CommonAPI::CallStatus> loadAsync(const std::string &_key, LoadAsyncCallback _callback, const CommonAPI::CallInfo *_info);


    virtual void getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const;

private:
    


};

} // namespace commonapi
} // namespace v1_0

#endif // COMMONAPI_Persistence_Service_DBUS_PROXY_HPP_

