/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_Persistence_Service_PROXY_BASE_HPP_
#define COMMONAPI_Persistence_Service_PROXY_BASE_HPP_

#include <v1_0/commonapi/PersistenceService.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <vector>

#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace commonapi {

class PersistenceServiceProxyBase
    : virtual public CommonAPI::Proxy {
public:

    typedef std::function<void(const CommonAPI::CallStatus&)> StoreAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> LoadAsyncCallback;



    virtual void store(const std::string &_key, const std::string &_value, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> storeAsync(const std::string &_key, const std::string &_value, StoreAsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void load(const std::string &_key, CommonAPI::CallStatus &_internalCallStatus, std::string &_value, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> loadAsync(const std::string &_key, LoadAsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr) = 0;
};

} // namespace commonapi
} // namespace v1_0

#endif // COMMONAPI_Persistence_Service_PROXY_BASE_HPP_
