/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1_0/commonapi/PersistenceServiceDBusProxy.hpp>

namespace v1_0 {
namespace commonapi {

std::shared_ptr<CommonAPI::DBus::DBusProxy> createPersistenceServiceDBusProxy(
	const CommonAPI::DBus::DBusAddress &_address,
	const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection) {
	return std::make_shared<PersistenceServiceDBusProxy>(_address, _connection);
}

INITIALIZER(registerPersistenceServiceDBusProxy) {
	CommonAPI::DBus::Factory::get()->registerProxyCreateMethod(
		PersistenceService::getInterface(),
		&createPersistenceServiceDBusProxy);
}

PersistenceServiceDBusProxy::PersistenceServiceDBusProxy(
	const CommonAPI::DBus::DBusAddress &_address,
	const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection)
	:	CommonAPI::DBus::DBusProxy(_address, _connection)
{
}



        void PersistenceServiceDBusProxy::store(const std::string &_key, const std::string &_value, CommonAPI::CallStatus &_internalCallStatus, const CommonAPI::CallInfo *_info) {
            CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> deploy_key(_key, static_cast<CommonAPI::DBus::StringDeployment*>(nullptr));
            CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> deploy_value(_value, static_cast<CommonAPI::DBus::StringDeployment*>(nullptr));
            CommonAPI::DBus::DBusProxyHelper<
                CommonAPI::DBus::DBusSerializableArguments<
                CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment >,
                CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment >
                >,
                CommonAPI::DBus::DBusSerializableArguments<
                >
            >::callMethodWithReply(
            *this,
            "store",
            "ss",
            (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
            deploy_key, deploy_value,
            _internalCallStatus);
        }
        std::future<CommonAPI::CallStatus> PersistenceServiceDBusProxy::storeAsync(const std::string &_key, const std::string &_value, StoreAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
            CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> deploy_key(_key, static_cast<CommonAPI::DBus::StringDeployment*>(nullptr));
            CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> deploy_value(_value, static_cast<CommonAPI::DBus::StringDeployment*>(nullptr));
            return CommonAPI::DBus::DBusProxyHelper<
                CommonAPI::DBus::DBusSerializableArguments<
                CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment >,
                CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment >
                >,
                CommonAPI::DBus::DBusSerializableArguments<
                >
            >::callMethodAsync(
            *this,
            "store",
            "ss",
            (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
            deploy_key, deploy_value,
            [_callback] (CommonAPI::CallStatus _status) {
            	_callback(_status);
            },
            std::make_tuple());
        }
        void PersistenceServiceDBusProxy::load(const std::string &_key, CommonAPI::CallStatus &_internalCallStatus, std::string &_value, const CommonAPI::CallInfo *_info) {
            CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> deploy_key(_key, static_cast<CommonAPI::DBus::StringDeployment*>(nullptr));
            CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> deploy_value(static_cast<CommonAPI::DBus::StringDeployment*>(nullptr));
            CommonAPI::DBus::DBusProxyHelper<
                CommonAPI::DBus::DBusSerializableArguments<
                CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment >
                >,
                CommonAPI::DBus::DBusSerializableArguments<
                    CommonAPI::Deployable<std::string,CommonAPI::DBus::StringDeployment>
                >
            >::callMethodWithReply(
            *this,
            "load",
            "s",
            (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
            deploy_key,
            _internalCallStatus,
            deploy_value);
            _value = deploy_value.getValue();
        }
        std::future<CommonAPI::CallStatus> PersistenceServiceDBusProxy::loadAsync(const std::string &_key, LoadAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
            CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> deploy_key(_key, static_cast<CommonAPI::DBus::StringDeployment*>(nullptr));
            CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> deploy_value(static_cast<CommonAPI::DBus::StringDeployment*>(nullptr));
            return CommonAPI::DBus::DBusProxyHelper<
                CommonAPI::DBus::DBusSerializableArguments<
                CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment >
                >,
                CommonAPI::DBus::DBusSerializableArguments<
                    CommonAPI::Deployable<std::string,CommonAPI::DBus::StringDeployment>
                >
            >::callMethodAsync(
            *this,
            "load",
            "s",
            (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
            deploy_key,
            [_callback] (CommonAPI::CallStatus _status, CommonAPI::Deployable<std::string, CommonAPI::DBus::StringDeployment> _value) {
            	_callback(_status, _value.getValue());
            },
            std::make_tuple(deploy_value));
        }


        void PersistenceServiceDBusProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
            ownVersionMajor = 1;
            ownVersionMinor = 0;
        }

        } // namespace commonapi
        } // namespace v1_0
